# version: '3.9'

services:
  # Database
  mariadb:
    container_name: mariadb-inception
    build: ./requirements/mariadb
    image: mariadb:inception
    env_file: .env
    volumes: [database:/var/lib/mysql]
    networks: [inception] 
    restart: always

  # Wordpress + PHP-FPM 8.2
  wordpress:
    container_name: wordpress-inception
    build: ./requirements/wordpress
    image: wordpress:inception
    env_file: .env
    volumes: [wordpress:/var/www/html]
    networks: [inception] 
    depends_on: [mariadb]
  
  # Web-Server
  nginx:
    container_name: nginx-inception
    build: ./requirements/nginx
    image: nginx:inception
    ports: ["443:443"]
    volumes: [wordpress:/var/www/html]
    networks: [inception]
    depends_on: [wordpress]

# Local directories mapping
volumes:
  wordpress:
    driver: local
    name: wordpress_vol
    driver_opts:
      type: none
      o: bind
      device: /home/sbocanci/data/wordpress_data
      # device: /home/sv/data/wordpress_data
  
  database:
    driver: local
    name: mariadb_vol
    driver_opts:
      type: none
      o: bind
      device: /home/sbocanci/data/mariadb_data
      # device: /home/sv/data/mariadb_data
  
# Shared network for all containers
networks:
  inception:
    name: inception_net
    driver: bridge
