version: '3'

services:

  wordpress:
    container_name: wordpress-the-one
    build: ./requirements/wordpress
    image: wordpress:the-one
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
  
volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      device: /home/sbocanci/data/wordpress_data
      o: bind
  